version: 2
sphinx:
  builder: html
  configuration: doc/conf.py
build:
  image: latest
python:
  version: 3.8
  install:
      - method: pip
        path: .
        requirements: doc/requirements.txt
  system_packages: true
