version: 2
sphinx:
  builder: html
  configuration: doc/conf.py
build:
  image: latest
python:
  version: 3.8
  install:
      - requirements: doc/requirements.txt
      - method: pip
        path: .
  system_packages: true
