language: python
cache:
    directories:
        - $HOME/.cache/pip
addons:
  apt:
    packages:
      - libatlas-base-dev
      - gfortran
python:
  - "2.7"
  - "3.5"
before_install:
  - mkdir -p $HOME/.cache/pip/wheels
  - travis_wait pip wheel --find-links=$HOME/.cache/pip/wheels --use-wheel --wheel-dir=$HOME/.cache/pip/wheels scipy
  - pip install --no-index --find-links=$HOME/.cache/pip/wheels scipy
install:
  - pip install -r requirements-dev.txt
script: python setup.py test
after_success:
  - bash <(curl -s https://codecov.io/bash)
